<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>9a28f2ce-d056-4fbc-b4cc-204b70bf669e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.16" />
  </ItemGroup>

</Project>
